#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	# Query the config value from /etc/config/modemmanager
	local enabled
	config_load modemmanager
	config_get enabled main enabled "1"

	if [ "$enabled" = "1" ]; then
		procd_open_instance "modem-manager"
		procd_set_param command /usr/bin/modem-manager
		procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
	fi
}

